---
title: "FINAL"
author: "Kirill Usoltsev"
date: "11/29/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(ggplot2)
library(FSA)
library(car)
library(tidyverse)
library(broom)
library(splines)
library(GGally)
library(sjPlot)
library(ggpubr)
library(webshot)
library(jtools)

setwd("~/Desktop/BIOINF2021/FINAL_PROJECT/spb_covid_study20-master/FINAL_PROJECT")
load("~/Desktop/BIOINF2021/FINAL_PROJECT/spb_covid_study20-master/FINAL_PROJECT/data/wave2/phone_survey/phone_survey_data.rdata")
load("~/Desktop/BIOINF2021/FINAL_PROJECT/spb_covid_study20-master/FINAL_PROJECT/data/wave2/test_results/other_tests/other_test_results_matched_to_phone_survey_ids.rdata")
```
```{r}

merged_data <- merge(other_test_results_matched_to_phone_survey_ids, phone_survey_data, by = "ID", all.y = T) 

merged_data$age_grouped <- cut(merged_data$age, breaks = c(17, 20, 25, 30, 35, 40, 45, 50,55, 60, 95), labels = c("18-20", "21-25", "26-30", "31-35", "36-40", "41-45", "46-50", "51-55", "56-60", "61+")) 
merged_data$age_grouped_who <- cut(merged_data$age, breaks = c(17, 44, 59, 74, 90, 95), labels = c("18-44", "45-59", "60-74", "75-90", "90+"))
#18-44 (молодые), 45-59 (средний возраст), 60-74 (пожилые) и 75-90 (старческий  возраст) ну и старше (долгожители)

factor_list <- c("male", "travelled", "used_transport", "smoking", "health_level", "lives_alone", "education_level", "age_grouped", "age_grouped_who", "no_pets", "dogs", "cats", "rodents", "birds", "other_pets", "not_sure_pets", "allergies", "chronical_diseases")

data <- merged_data %>% 
  # mutate(log_IgE = log10(IgE_general_quantitative)) %>% 
  mutate(across(c("male", "travelled", "used_transport", "smoking", "health_level", "lives_alone", "education_level", "age_grouped", "age_grouped_who", "no_pets", "dogs", "cats", "rodents", "birds", "other_pets", "not_sure_pets", "allergies", "chronical_diseases"), function(x) x %>% as.factor())) %>% 
  mutate( log_IgE = log1p(IgE_general_quantitative))

Hmisc::describe(data)

ggplot(data, aes(x = no_pets, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = dogs, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = cats, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = rodents, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = birds, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = other_pets, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
# любопытно, что IgE, кажется, связан с полом (выше у мужчин)
ggplot(data, aes(x = male, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
ggplot(data, aes(x = age_grouped_who, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
# education_level
ggplot(data, aes(x = education_level, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
# lives_alone
ggplot(data, aes(x = lives_alone, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
# district
ggplot(data, aes(x = district, y = log_IgE)) +
  geom_boxplot(notch = TRUE)
# health_level
ggplot(data, aes(x = health_level, y = log_IgE)) +
  geom_boxplot(notch = TRUE)

```


```{r}

fit0 <- glm(log_IgE ~ age + male + dogs + cats + rodents + birds + other_pets, data = data)
summary(fit0)
plot_summs(fit0, scale = TRUE)
```
Кажется, уровень IgE зависит от пола и наличия грызунов.
```{r}
# DOGS
#ggplot(data, aes(x = chronical_diseases, fill = dogs)) +
#    geom_bar(position = "fill")

#ggplot(data, aes(x = age_grouped_who, fill = dogs)) +
#    geom_bar(position = "fill")

#ggplot(data, aes(x = health_level, fill = dogs)) +
#    geom_bar()
#ggplot(data, aes(x = education_level, fill = dogs)) +
#    geom_bar(position = "fill")
#ggplot(data, aes(x = smoking, fill = dogs)) +
#    geom_bar(position = "fill")
#ggplot(data, aes(x = smoked_previously, fill = dogs)) +
#    geom_bar(position = "fill")
#ggplot(data, aes(x = dogs, y = cigarettes_per_day)) +
#    geom_boxplot()
#ggplot(data, aes(x = dogs, y = Atherogenic_index)) +
#    geom_boxplot()
#ggplot(data, aes(x = dogs, y = Cholesterin)) +
#    geom_boxplot()
#ggplot(data, aes(x = dogs, y = VitaminD)) +
#    geom_boxplot()

#fit1 <- glm(data = data, dogs ~ age_grouped_who+male+smoking+chronical_diseases, family = "binomial")
#summary(fit1)
#plot_summs(fit1, scale = TRUE)
```



