---
title: "RF_Kulanin"
author: "Pablo"
date: "17 12 2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(randomForest)
library(datasets)
library(caret)
library(tidyverse)
library(dlstats)
library(pkgsearch) 
library(cutoff)
library(pROC)
library(ggplot2)
```

```{r}
B = test_B_results_matched_to_phone_survey_ids
O = select(other_test_results_matched_to_phone_survey_ids, "ID","neutralizing_antibodies_quantitative")
C = select(test_C_results_matched_to_phone_survey_ids, -2, -4)
D = select(test_D_results_matched_to_phone_survey_ids, -2, -4)

phone_survey_data %>% 
  mutate(across(!c("interviewer", "interview_duration", "age", "cigarettes_per_day", "coffee_cups_per_day", "num_people_home", "error_in_randomization", "interview_date"), function(x) x %>% as.factor())) -> phone_survey

merged_data <- merge(phone_survey_data, B, by = "ID", all.y = T)
merged_dataFULL = merge(merged_data, C, by = "ID", all.y = T)
MDF1 = merge(merged_dataFULL, D, by = "ID", all.y = T)
MDF = merge(MDF1, O, by = "ID", all.y = T)
MDF = cbind(MDF,"NAB"= (as.factor(MDF$neutralizing_antibodies_quantitative >= 80)))
MDF = as.data.frame(MDF)
```

```{r}

ggplot(MDF, aes(y = IgG_testB_quantitative, x = neutralizing_antibodies_quantitative)) +
  geom_point() + 
  ylab("IgG общие к Covid-19 (test B)") + 
  xlab("NAB") + 
  scale_x_log10()+
  theme_bw()

ggplot(MDF, aes(y = IgA_or_G_or_M_testC_quantitative, x = neutralizing_antibodies_quantitative)) +
  geom_point() + 
  ylab("IgG + IgM + IgA к Covid-19 (test C)") + 
  xlab("NAB") + 
  scale_x_log10()+
  theme_bw()

ggplot(data = MDF, aes(y = IgG_or_M_testD_quantitative, x = neutralizing_antibodies_quantitative)) +
  geom_jitter(size = 0.8) +
  ylab("ELISA VECTORBEST") + 
  xlab("Neutralizing antibodies")+
  theme_bw() +
  scale_x_continuous(breaks = c(5, 10, 20, 40, 80, 160, 320, 640), trans = "log2")
```

```{r}
COR_NAB_ELISA_VECTORBEST = (cor.test(MDF$neutralizing_antibodies_quantitative, MDF$IgG_or_M_testD_quantitative, method = "spearman", conf.level = "95"))$estimate

COR_NAB_ELISA_CORONAPASS = (cor.test(MDF$neutralizing_antibodies_quantitative, MDF$IgA_or_G_or_M_testC_quantitative, method = "spearman"))$estimate

COR_NAB_CMIA_ABBOTT = (cor.test(MDF$neutralizing_antibodies_quantitative, MDF$IgG_testB_quantitative, method = "spearman"))$estimate

```

```{r}
NAB_TESTD = lm(neutralizing_antibodies_quantitative~IgG_or_M_testD_quantitative, MDF)

summary(NAB_TESTD)

NAB_TESTC=lm(neutralizing_antibodies_quantitative ~ IgA_or_G_or_M_testC_quantitative, MDF)

summary(NAB_TESTC)

NAB_TESTB = lm(neutralizing_antibodies_quantitative ~ IgG_testB_quantitative, MDF)

summary(NAB_TESTB)
```

```{r}
data = test_nab

set.seed(100)

ind <- sample(2, nrow(data), replace = TRUE, prob = c(0.8, 0.2))

train <- data[ind==1,]
test <- data[ind==2,]

rf <- randomForest(`MNT 1:80`~ vector+abbott+genetico, data=train, proximity=TRUE)

print(rf)

p1 <- predict(rf, train)

confusionMatrix(p1, train$ `MNT 1:80`)

p2 <- predict(rf, test)

confusionMatrix(p2, test$`MNT 1:80`)

plot(rf)

hist(treesize(rf),
     main = "No. of Nodes for the Trees",
     col = "green")
varImpPlot(rf,
           sort = T,
           n.var = 10,
           main = "Top 10 - Variable Importance")
  importance(rf)

pred_prob_rf <-as.data.frame( predict(rf, test, type="prob"))
# ROC value
roc_rf <- pROC::roc(test$`MNT 1:80`, pred_prob_rf$`SARS-Cov-2`)

# Confusion Matrix for Random Forest Model
roc_rf

caTools::colAUC(pred_prob_rf$`SARS-Cov-2`, test$`MNT 1:80`, plotROC = T)

```

```{r}
set.seed(100)

ind <- sample(2, nrow(data), replace = TRUE, prob = c(0.8, 0.2))

train <- data[ind==1,]
test <- data[ind==2,]

rf_vector <- randomForest(`MNT 1:80`~ vector, data=train, proximity=TRUE)

print(rf_vector)

p1_vector <- predict(rf_vector, train)

confusionMatrix(p1_vector, train$ `MNT 1:80`)

p2_vector <- predict(rf_vector, test)

confusionMatrix(p2_vector, test$`MNT 1:80`)

plot(rf_vector)

pred_prob_rf_vector <-as.data.frame( predict(rf_vector, test, type="prob"))

# ROC value
roc_rf_vector <- pROC::roc(test$`MNT 1:80`, pred_prob_rf_vector$`SARS-Cov-2`)

# Confusion Matrix for Random Forest Model
roc_rf_vector
```

```{r}
set.seed(100)

ind <- sample(2, nrow(data), replace = TRUE, prob = c(0.8, 0.2))

train <- data[ind==1,]
test <- data[ind==2,]

rf_abbott <- randomForest(`MNT 1:80`~ abbott, data=train, proximity=TRUE)

print(rf_abbott)

p1_abbott <- predict(rf_abbott, train)

confusionMatrix(p1_abbott, train$ `MNT 1:80`)

p2_abbott <- predict(rf_abbott, test)

confusionMatrix(p2_abbott, test$`MNT 1:80`)

plot(rf_abbott)

pred_prob_rf_abbott <-as.data.frame( predict(rf_abbott, test, type="prob"))

# ROC value
roc_rf_abbott <- pROC::roc(test$`MNT 1:80`, pred_prob_rf_abbott$`SARS-Cov-2`)

# Confusion Matrix for Random Forest Model
roc_rf_abbott
```

```{r}
set.seed(100)

ind <- sample(2, nrow(data), replace = TRUE, prob = c(0.8, 0.2))

train <- data[ind==1,]
test <- data[ind==2,]

rf_genetico <- randomForest(`MNT 1:80`~ genetico, data=train, proximity=TRUE)

print(rf_genetico)

p1_genetico <- predict(rf_genetico, train)

confusionMatrix(p1_genetico, train$ `MNT 1:80`)

p2_genetico <- predict(rf_genetico, test)

confusionMatrix(p2_genetico, test$`MNT 1:80`)

plot(rf_genetico)


pred_prob_rf_genetico <-as.data.frame( predict(rf_genetico, test, type="prob"))

# ROC value
roc_rf_genetico <- pROC::roc(test$`MNT 1:80`, pred_prob_rf_genetico$`SARS-Cov-2`)

# Confusion Matrix for Random Forest Model
roc_rf_genetico

```

```{r}
caTools::colAUC(pred_prob_rf_genetico$`SARS-Cov-2`, test$`MNT 1:80`, plotROC = T)

caTools::colAUC(pred_prob_rf_abbott$`SARS-Cov-2`, test$`MNT 1:80`, plotROC = T)

caTools::colAUC(pred_prob_rf_vector$`SARS-Cov-2`, test$`MNT 1:80`, plotROC = T)
```

```{r}
roc.list <- roc(`MNT 1:80` ~ genetico + abbott + vector, data, auc=T)
ggroc(roc.list)+
  theme_classic()
```

